version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    image: pp-nginx
    depends_on:
      - frontend
      - user
      - matching
      - collaboration
      - history
      - question
      - communication
    ports:
      - 80:80
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    image: pp-frontend
    ports:
      - 3000:3000
  user:
    build:
      context: .
      dockerfile: ./docker/user.Dockerfile
    image: pp-user
    env_file:
      - ./user-service/.env
    ports:
      - 8000:8000
  matching:
    build:
      context: .
      dockerfile: ./docker/matching.Dockerfile
    image: pp-matching
    depends_on:
      - redis-matching
    environment:
      - REDIS_URL=redis://redis-matching:6379
      - URI_COLLAB_SVC=http://collaboration:8002
    ports:
      - 8001:8001
  collaboration:
    build:
      context: .
      dockerfile: ./docker/collaboration.Dockerfile
    image: pp-collaboration
    depends_on:
      - redis-collab
    environment:
      - REDIS_URL=redis://redis-collab:6379
      - URI_QUESTION_SVC=http://question:8004
      - URI_HISTORY_SVC=http://history:8003
    ports:
      - 8002:8002
  history:
    build:
      context: .
      dockerfile: ./docker/history.Dockerfile
    image: pp-history
    env_file:
      - ./history-service/.env
    ports:
      - 8003:8003
  question:
    build:
      context: .
      dockerfile: ./docker/question.Dockerfile
    image: pp-question
    ports:
      - 8004:8004
  communication:
    build:
      context: .
      dockerfile: ./docker/communication.Dockerfile
    image: pp-communication
    ports:
      - 8005:8005
  redis-matching:
    image: 'redis:alpine'
  redis-collab:
    image: 'redis:alpine'
