apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-svc
  labels:
    app: collaboration-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-svc
  template:
    metadata:
      labels:
        app: collaboration-svc
    spec:
      containers:
        - name: collaboration-svc
          image: 272468461328.dkr.ecr.ap-southeast-1.amazonaws.com/cc-collaboration:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: REDIS_URL
              value: 'redis://redis-collaboration.opyeey.ng.0001.apse1.cache.amazonaws.com:6379'
            - name: URI_QUESTION_SVC
              value: 'http://question-svc:8004'
            - name: URI_HISTORY_SVC
              value: 'http://history-svc:8003'
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: collaboration-svc
  name: collaboration-svc
spec:
  selector:
    app: collaboration-svc
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
