apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-svc
  labels:
    app: matching-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-svc
  template:
    metadata:
      labels:
        app: matching-svc
    spec:
      containers:
        - name: matching-svc
          image: cc-matching
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: REDIS_URL
              value: 'redis://redis-matching:6379'
            - name: URI_COLLAB_SVC
              value: 'http://collaboration-svc:8002'

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: matching-svc
  name: matching-svc
spec:
  selector:
    app: matching-svc
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: 8001
