name: Deploy to production

on:
  pull_request:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - 'common/**'
              - 'k8s/prod/frontend-deployment.yaml'
            user-svc:
              - 'user-service/**'
              - 'common/**'
              - 'k8s/prod/user-deployment.yaml'
            matching-svc:
              - 'matching-service/**'
              - 'common/**'
              - 'k8s/prod/matching-deployment.yaml'
            ingress:
              - 'k8s/prod/ingress.yaml'

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.3'
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update kube config
        run: aws eks update-kubeconfig --name pp-cluster --region ap-southeast-1

      - name: Frontend - Build and push docker image to Amazon ECR and deploy to Amazon EKS
        if: steps.filter.outputs.frontend == 'true'
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: pp-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f docker/frontend.Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY
          kubectl apply -f k8s/prod/frontend-deployment.yaml
          kubectl rollout restart deploy frontend

      - name: User Service - Build and push docker image to Amazon ECR and deploy to Amazon EKS
        if: steps.filter.outputs.user-svc == 'true'
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: pp-user
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f docker/user.Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY
          kubectl apply -f k8s/prod/user-deployment.yaml
          kubectl rollout restart deploy user-svc

      - name: Matching Service - Build and push docker image to Amazon ECR and deploy to Amazon EKS
        if: steps.filter.outputs.matching-svc == 'true'
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: pp-matching
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f docker/matching.Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY
          kubectl apply -f k8s/prod/matching-deployment.yaml
          kubectl rollout restart deploy matching-svc

      - name: Ingress - deploy to Amazon EKS
        if: steps.filter.outputs.ingress == 'true'
        run: |
          kubectl apply -f k8s/prod/ingress.yaml
