name: Test and Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [frontend, user-service, collaboration-service, matching-service, question-service, history-service, communication-service]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
      - run: |
          npm ci
          npm test --if-present
          npm run build --if-present
        working-directory: ${{ matrix.dir }}
